name: CI/CD

on:
  push:
    branches: [main] # Trigger on pushes to the main branch
  pull_request:
    branches: [main] # Also trigger on pull requests to the main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Check out the code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format (check only)
        run: npm run format -- --check

      - name: Build project
        run: npm run build
